name: Onigiri Client (Prod)

on: workflow_dispatch

permissions:
  contents: read

defaults:
  run:
    working-directory: src

jobs:
  build_and_deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build Shared Lib
        run: npm run build-shared-lib

      - name: Build Page editor
        run: npm run build-page-editor

      - name: Build App
        run: npm run build-onigiri-prod

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=src/dist/onigiri/browser --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
